version: '3.8'

services:
  pdf-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PUPPETEER_DEFAULT_TIMEOUT=60000
      - PUPPETEER_PROTOCOL_TIMEOUT=60000
      - CHROMIUM_PATH=/usr/bin/chromium
      - PUPPETEER_MAX_CONCURRENT_PAGES=15
